// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBegOLb2tJklBKaWn_xClBGC772gweFOmU',
    appId: '1:565147380687:web:3bf19dd374453c762580ba',
    messagingSenderId: '565147380687',
    projectId: 'water-delivery-7ad02',
    authDomain: 'water-delivery-7ad02.firebaseapp.com',
    storageBucket: 'water-delivery-7ad02.appspot.com',
    measurementId: 'G-C59RZB29S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZaKU6H3AsHKI2hSfxHWDsbKrmYMwmaoY',
    appId: '1:565147380687:android:c7e724f929d550622580ba',
    messagingSenderId: '565147380687',
    projectId: 'water-delivery-7ad02',
    storageBucket: 'water-delivery-7ad02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqojcVthhicfijuwqtTebVTPwFaEt-fX8',
    appId: '1:565147380687:ios:a5f0360bdc6655ea2580ba',
    messagingSenderId: '565147380687',
    projectId: 'water-delivery-7ad02',
    storageBucket: 'water-delivery-7ad02.appspot.com',
    iosBundleId: 'com.example.waterDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBegOLb2tJklBKaWn_xClBGC772gweFOmU',
    appId: '1:565147380687:web:16ccf1f144f10db72580ba',
    messagingSenderId: '565147380687',
    projectId: 'water-delivery-7ad02',
    authDomain: 'water-delivery-7ad02.firebaseapp.com',
    storageBucket: 'water-delivery-7ad02.appspot.com',
    measurementId: 'G-KVMRQXRXT9',
  );
}
